# -*- coding: utf-8 -*-
"""genai_gemini_day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6C4onYR99v2iN44Xze1BniKoWVQKaDT
"""

!pip install -q -U google-generativeai

import google.generativeai as genai

genai.configure(api_key="AIzaSyA4tfzx6dbADxfJnTQ_qIljYNi4BcY44uI")

for i in genai.list_models():
  print(i.name)

model=genai.GenerativeModel("gemini-pro")

res=model.generate_content("district in tamilnadu")

print(res.text)

know=model.generate_content("what is gdp of tamilnadu and how it achieved it")
print(know.text)

internet=model.generate_content("what is arpanet")
print(internet.text)

!pip install -q -U google-generativeai

genai.configure(api_key="AIzaSyA4tfzx6dbADxfJnTQ_qIljYNi4BcY44uI")

import google.generativeai as genai

vision_model=genai.GenerativeModel("gemini-1.5-flash")

from PIL import Image
img=Image.open("/content/download.jpg")

img

res=vision_model.generate_content(["what the image telling",img])

print(res.text)

